CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    event_date DATE NOT NULL,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE event_users (
    event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, user_id)
);

ALTER TABLE ratings
    ADD COLUMN user_id BIGINT REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE ratings
    ADD COLUMN event_id BIGINT REFERENCES events (id) ON DELETE SET NULL;

CREATE INDEX idx_events_restaurant_id
    ON events (restaurant_id);

CREATE INDEX idx_ratings_user_id
    ON ratings (user_id);

CREATE INDEX idx_ratings_event_id
    ON ratings (event_id);
